#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

// =============================================================================
// === GAME CONFIGURATION & BALANCING VALUES                                 ===
// =============================================================================
// This file contains all the core variables for tuning the game's economy,
// military, and AI. Change these values to alter the simulation's behavior.
// =============================================================================

// --- WAR SIMULATION CONSTANTS ---
#define WAR_ONGOING 0
#define EMPIRE_WINS 1
#define REBELS_WIN 2


// --- GUI & TIMING ---
#define LOG_SECTION_SIZE 250
#define SIMULATION_TICK_SECONDS 5       // Time in seconds for each simulated hour.
#define LOG_CLEAR_FREQUENCY_HOURS 4     // How often to clear old log entries.
#define FADE_SPEED 0.05f                // Opacity change per frame for story transitions.

// --- POPULATION & WORLD ---
#define INITIAL_POPULATION 13000        // Starting population of the empire.
#define STARTING_BRONZE 80              // Bronze coins a newborn human starts with.
#define POPULATION_GROWTH_FLOOR 10000   // Below this population, deaths won't exceed births.
#define HUMAN_ARRAY_GROWTH_FACTOR 1.5   // How much to grow the human array when it's full.
#define DAYS_IN_MONTH 30.0              // Used for calculating monthly rates.
#define ACTIVE_HOURS_PER_DAY 12.0       // Used for distributing daily births/deaths over active hours.
#define DAILY_NATURAL_DEATH_RATE_PER_1000 0.008 // The base daily death rate.
#define FOOD_SURPLUS_PER_BIRTH 500.0    // How much surplus food is needed to generate one birth.
#define NUM_KINGDOMS 8                  // 1 Empire + 7 Successor Kingdoms

// --- UNREST & REBELLION ---
#define REBELLION_THRESHOLD 2000         // Unrest level for the Empire to collapse.
#define DISSENT_THRESHOLD 100           // Unrest level for citizens to start becoming rebels.
#define HOURLY_UNREST_DECAY_CHANCE_DIVISOR 24 // 1 in X chance per hour for unrest to decrease by 1.
#define WELL_FED_UNREST_REDUCTION_AMOUNT 1 // Unrest reduction if food is plentiful.
#define UNREST_GAIN_FROM_TAXES 12        // Unrest generated by the act of collecting taxes.
#define UNABLE_TO_PAY_TAX 8
#define UNREST_GAIN_FROM_FAMINE 10       // Unrest spike when a kingdom runs out of food.
#define MAX_NEW_REBELS_PER_DAY 200      // The maximum number of people who can become rebels in one day.
#define REBEL_CHANCE_DIVISOR 5000       // The roll for a person to become a rebel is rand() % THIS_VALUE. A lower number means more rebels.
#define MAX_UNREST_FOR_REBEL_CONVERSION 4000 // Caps the effective unrest level used in rebel conversion checks.
#define REBEL_LEADER_SPAWN_CHANCE_PERCENT 2 // The chance (out of 100) for a new rebel to become a charismatic leader.
#define SOLDIER_DEFECTION_CHANCE_MODIFIER 0.9f // Multiplier for soldier defection chance vs civilian.

// --- ECONOMY & JOBS ---

// Civilians
#define JOB_FARMER 1
#define JOB_BUTCHER 2
#define JOB_LUMBERJACK 3
#define JOB_MINER 4
#define JOB_BLACKSMITH 5

// Military
#define JOB_SWORDSMAN 6
#define JOB_ARCHER 7
#define JOB_CAVALRY 8

// Other
#define JOB_REBEL 9

#define TAX_RATE_PER_PERSON 1           // Bronze coins collected from each person per day.
#define FARMER_FOOD_PRODUCTION 2        // Food generated by one farmer per day.
#define LUMBERJACK_WOOD_PRODUCTION 1    // Wood generated by one lumberjack per day.
#define BUTCHER_MEAT_PRODUCTION 2
#define MINER_STONE_PRODUCTION 3        // Stone generated by one miner per day (if they don't find metal).
#define MINER_METAL_PRODUCTION 3        // Metal generated by one miner per day (if they find metal).
#define MINER_METAL_CHANCE_PERCENT 25   // The chance (out of 100) for a miner to find metal instead of stone.
#define BLACKSMITH_METAL_NEEDS 3        // The number of metals needed to produce weapons
#define FAMINE_POPULATION_LOSS_PERCENT 5 // The percentage of the population that dies during a famine event.
#define WORK_START_HOUR 4               // Hour of the day when work starts.
#define WORK_END_HOUR 22                // Hour of the day when work ends.
#define EAT_HUNGER_THRESHOLD 40         // Hunger level at which a person will eat.
#define FOOD_COST 15                    // Bronze cost to eat.
// Initial Kingdom Resources
#define INITIAL_EMPIRE_FOOD 800000
#define INITIAL_EMPIRE_WOOD 1000
#define INITIAL_EMPIRE_STONE 1000
#define INITIAL_EMPIRE_METAL 500
#define INITIAL_EMPIRE_TREASURY 1000
#define INITIAL_EMPIRE_MORALE 60
#define INITIAL_SUCCESSOR_FOOD 500
#define INITIAL_SUCCESSOR_WOOD 100
#define INITIAL_SUCCESSOR_TREASURY 1000
#define INITIAL_SUCCESSOR_MORALE 75

// --- MILITARY & COMBAT ---
#define MILITARY_EXTRA_FOOD_CONSUMPTION 1 // EXTRA food consumed by one soldier per day (in addition to their base consumption).
#define GENERAL_SPAWN_CHANCE_PERCENT 2  // The chance (out of 100) for a new soldier to be a General.
#define INITIAL_GENERAL_LIMIT 3         // Maximum number of generals at the start of the game.
#define GENERAL_COMBAT_BONUS 1.15f      // A multiplier for army strength for each General present (1.15 = +15%).
#define REBEL_LEADER_COMBAT_BONUS 1.25f // A multiplier for rebel strength for each Leader present (1.25 = +25%).
#define REBEL_BASE_STRENGTH_MODIFIER 1.1f // Base combat advantage for rebels.
#define ELEMENT_OF_SURPRISE 1.05
#define ORAGINIZED_COMMAND 1.1
// Resource Costs for Recruitment
#define COST_SWORDSMAN_METAL 10
#define COST_ARCHER_WOOD 10
#define COST_CAVALRY_METAL 15
#define COST_CAVALRY_FOOD 10
// Battle & Skirmish
#define HOURLY_SKIRMISH_BASE_CHANCE_PERCENT 50 // Base chance of a skirmish happening each hour if rebels are present.
#define MORALE_LOSS_FROM_SKIRMISH 1
#define MORALE_GAIN_ON_VICTORY 5
#define MORALE_LOSS_ON_DEFEAT 10
#define REBELS_IN_SKIRMISH 0.35
#define SOLDIERS_IN_SKIRMISH 0.25
// Daily Morale
#define MORALE_FOOD_SURPLUS_MULTIPLIER 2
#define MORALE_GAIN_FROM_SURPLUS 1
#define MORALE_LOSS_FROM_UNREST 1
#define MINIMUM_MORALE_FOR_UNREST_LOSS 20
// Civil War
#define CIVIL_WAR_MINIMUM_REBELS 100
#define CIVIL_WAR_REBEL_TO_SOLDIER_RATIO 0.75f

// --- RANDOM EVENTS ---
#define DAILY_RANDOM_EVENT_CHANCE_PERCENT 7 // The chance (out of 100) for a random event to occur each day.
#define TOTAL_RANDOM_EVENTS 6               // The number of possible random events.
#define PLAGUE_POPULATION_LOSS_PERCENT 0.1   // The percentage of the population that dies during a plague event.
#define BARBARIAN_POPULATION_LOSS_PERCENT 0.02 // The percentage of the population that dies during a barbarian raid.
// Event-specific values
#define HARVEST_BASE_FOOD_GAIN 500
#define HARVEST_POPULATION_FOOD_MULTIPLIER 0.5f
#define GOLD_DISCOVERY_BRONZE_BONUS 150
#define PLAGUE_UNREST_GAIN 8
#define DROUGHT_UNREST_GAIN 10
#define BARBARIAN_RAID_RESOURCE_LOSS_PERCENT 0.8f // Keep 80% (lose 20%)
#define BARBARIAN_RAID_UNREST_GAIN 5
#define POLITICAL_INTRIGUE_UNREST_GAIN 2

// --- Player ---
#define PLAYER_FESTIVAL_COST 150000
#define PLAYER_FESTIVAL_UNREST_REDUCTION 50
#define PLAYER_HEALTH 200

// --- AI GOVERNOR ---
#define AI_ACTION_THRESHOLD 0.4f        // The urgency score needed for the AI to take major action.
#define AI_CRITICAL_FOOD_DAYS_THRESHOLD 2 // If food is below this many days, it's a catastrophe.
#define AI_ARMY_SIZE_GOAL_PERCENT 0.08f // AI will try to maintain an army size of 8% of the population.
#define AI_FESTIVAL_COST 500            // The treasury cost for the AI to host a festival.
#define AI_FESTIVAL_UNREST_REDUCTION 45 // The amount of unrest reduced by the AI's festival.
#define AI_FARMER_CONVERSION_COUNT 50   // Number of workers the AI converts to farmers during a food crisis.
#define AI_FOOD_DAYS_THRESHOLD 1        // AI will consider food a problem if it has less than this many days of food.
#define AI_STABILITY_ACTION_THRESHOLD 0.1f // AI will act on unrest if its score is above this.

// --- DIVINE INTERVENTION (The "Borrow from God" System) ---
#define AI_DIVINE_INTERVENTION_TREASURY_THRESHOLD 3000 // AI must have at least this much in treasury to even consider an intervention.
#define PENALTY_DURATION_DAYS 10                       // How many days the negative collateral effect lasts.

// Intervention 1: Reinforcements
#define DI_COST_REINFORCEMENTS 2000                    // Treasury cost.
#define DI_REINFORCEMENTS_COUNT 20                     // How many soldiers are created.
#define DI_PENALTY_TAX_MODIFIER 0.75f                  // Collateral: Kingdom only collects 75% of normal taxes.

// Intervention 2: Sustenance
#define DI_COST_SUSTENANCE 1500                        // Treasury cost.
#define DI_SUSTENANCE_FOOD_AMOUNT 1000                 // How much food is granted.
#define DI_PENALTY_PRODUCTION_MODIFIER 0.80f           // Collateral: All resource production is at 80% efficiency.

// Intervention 3: Absolution
#define DI_COST_ABSOLUTION 2500                        // Treasury cost.
#define DI_ABSOLUTION_UNREST_REDUCTION 20              // How much unrest is removed.
#define DI_ABSOLUTION_UNREST_THRESHOLD 300             // Can only be used if unrest is ABOVE this value.
#define DI_PENALTY_MORALE_DROP 10                      // Collateral: Army morale drops from the perceived weakness.

#endif // GAME_CONFIG_H